name: CI - Main

on:
    push:
        branches:
            - main

jobs:
    biome:
        name: Check Formatting
        timeout-minutes: 15
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Biome
              uses: biomejs/setup-biome@v2
            - name: Run Biome
              run: biome ci .
